version: "3.10"

services:
  db:
    image: ankane/pgvector:pg16
    container_name: guam_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: guam_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: guam_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  api:
    build:
      context: ..
      dockerfile: infra/dockerfiles/api.Dockerfile
    container_name: guam_api
    restart: unless-stopped
    depends_on:
      - db
      - redis
    env_file:
      - ../.env
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/guam_db
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ../:/app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"

  worker:
    build:
      context: ..
      dockerfile: infra/dockerfiles/worker.Dockerfile
    container_name: guam_worker
    restart: unless-stopped
    depends_on:
      - api
      - redis
    env_file:
      - ../.env
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/guam_db
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ../:/app

  web:
    build:
      context: ../web
      dockerfile: ../infra/dockerfiles/web.Dockerfile
    container_name: guam_web
    restart: unless-stopped
    depends_on:
      - api
    env_file:
      - ../.env
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ../web:/app
      - /app/node_modules

volumes:
  postgres_data:

